name: Bump Version

on:
  pull_request:
    branches:
      - main

jobs:
  prebuild:
    name: Bump Version (prebuild)
    runs-on: ubuntu-latest

    # Minimum permissions required by skip-duplicate-actions
    permissions:
      actions: write
      contents: read

    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}

    steps:
      - name: Skip Duplicate Actions
        id: skip_check
        uses: fkirc/skip-duplicate-actions@v5.3.0
        with:
          concurrent_skipping: "same_content_newer"
          paths_ignore: '["**/README.md"]'

  build:
    name: Bump Version (build)
    needs: prebuild
    if: needs.prebuild.outputs.should_skip != 'true'
    runs-on: ubuntu-latest

    # Map a step output to a job output
    outputs:
      new_tag: ${{ steps.tag_check.outputs.new_tag || '' }}
      old_tag: ${{ steps.tag_check.outputs.old_tag || '' }}
      part: ${{ steps.tag_check.outputs.part || 'none' }}

    steps:
      # - name: "PR commits + 1"
      #   id: pr_commit_check
      #   run: echo "PR_FETCH_DEPTH=$(( ${{ github.event.pull_request.commits }} + 1 ))" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          # depth is base from total commit exist in PR
          # fetch-depth: ${{ steps.pr_commit_check.outputs.PR_FETCH_DEPTH }}
          fetch-depth: ${{ github.event.pull_request.commits }}

      - name: Dump Git Log
        run: git --no-pager log --oneline

      - name: Bump Version Check
        id: tag_check
        uses: anothrNick/github-tag-action@1.61.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # checkout from the lastest base branch commit before split to this PR branch
          DEFAULT_BRANCH: ${{ github.event.pull_request.base.sha }}
          BRANCH_HISTORY: full
          DEFAULT_BUMP: none
          WITH_V: true
          DRY_RUN: true

  postbuild:
    name: Bump Version (postbuild)
    needs: [prebuild, build]
    # only proceed if got new tag
    if: (needs.build.outputs.part != 'none' && (needs.build.outputs.new_tag != needs.build.outputs.old_tag))
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}

      - name: Update package.json ${{ needs.build.outputs.new_tag }}
        # run: npm version --no-git-tag-version ${{ needs.build.outputs.new_tag }}
        run: yarn version --no-git-tag-version --new-version ${{ needs.build.outputs.new_tag }}

      - name: Auto Commit with Tag Publish
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          tagging_message: ${{ needs.build.outputs.new_tag }}
          # prevent workflow re-trigger on commit push 
          # reference: https://docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs
          commit_message: |
            automate: update version ${{ needs.build.outputs.new_tag }}

            [ci skip]